
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.craiglowery.java.vlib.filter;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BOOLEAN_NOT_OPERATOR = 5;
  public static final int ATTRIBUTE_NAME_STRING = 13;
  public static final int OPEN_BRACKET_TOKEN = 8;
  public static final int TRUE_TOKEN = 10;
  public static final int COMMA_TOKEN = 12;
  public static final int FALSE_TOKEN = 11;
  public static final int CLOSE_BRACKET_TOKEN = 9;
  public static final int GENERAL_VALUE_INTEGER = 16;
  public static final int CLOSE_PAREN_TOKEN = 7;
  public static final int EOF = 0;
  public static final int OPEN_PAREN_TOKEN = 6;
  public static final int BOOLEAN_AND_OPERATOR = 4;
  public static final int error = 1;
  public static final int COMPARISON_OPERATOR = 2;
  public static final int TIMESTAMP_VALUE_STRING = 17;
  public static final int BOOLEAN_OR_OPERATOR = 3;
  public static final int GENERAL_VALUE_DOUBLE = 15;
  public static final int GENERAL_VALUE_STRING = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMPARISON_OPERATOR",
  "BOOLEAN_OR_OPERATOR",
  "BOOLEAN_AND_OPERATOR",
  "BOOLEAN_NOT_OPERATOR",
  "OPEN_PAREN_TOKEN",
  "CLOSE_PAREN_TOKEN",
  "OPEN_BRACKET_TOKEN",
  "CLOSE_BRACKET_TOKEN",
  "TRUE_TOKEN",
  "FALSE_TOKEN",
  "COMMA_TOKEN",
  "ATTRIBUTE_NAME_STRING",
  "GENERAL_VALUE_STRING",
  "GENERAL_VALUE_DOUBLE",
  "GENERAL_VALUE_INTEGER",
  "TIMESTAMP_VALUE_STRING"
  };
}

