
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package com.craiglowery.java.vlib.tuple.filterexp;

/** CUP generated class containing symbol constants. */
public class StringExpressionSymbols {
  /* terminals */
  public static final int INTEGER = 12;
  public static final int TRUE = 9;
  public static final int COMPARISON_OPERATOR = 2;
  public static final int STRING = 11;
  public static final int EOF = 0;
  public static final int ATTRIBUTE = 5;
  public static final int DOUBLE = 13;
  public static final int NOT_OPERATOR = 8;
  public static final int OR_OPERATOR = 4;
  public static final int FALSE = 10;
  public static final int AND_OPERATOR = 3;
  public static final int error = 1;
  public static final int OPENPAREN = 6;
  public static final int CLOSEPAREN = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMPARISON_OPERATOR",
  "AND_OPERATOR",
  "OR_OPERATOR",
  "ATTRIBUTE",
  "OPENPAREN",
  "CLOSEPAREN",
  "NOT_OPERATOR",
  "TRUE",
  "FALSE",
  "STRING",
  "INTEGER",
  "DOUBLE"
  };
}

